// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (
  framework_id,
  name,
  scope,
  start_date,
  due_date,
  status,
  created_by
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, framework_id, name, scope, start_date, due_date, status, created_by, created_at, updated_at
`

type CreateAssessmentParams struct {
	FrameworkID uuid.UUID        `json:"framework_id"`
	Name        string           `json:"name"`
	Scope       string           `json:"scope"`
	StartDate   time.Time        `json:"start_date"`
	DueDate     time.Time        `json:"due_date"`
	Status      AssessmentStatus `json:"status"`
	CreatedBy   uuid.UUID        `json:"created_by"`
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.FrameworkID,
		arg.Name,
		arg.Scope,
		arg.StartDate,
		arg.DueDate,
		arg.Status,
		arg.CreatedBy,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.Name,
		&i.Scope,
		&i.StartDate,
		&i.DueDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssessmentItemsFromControlRecords = `-- name: CreateAssessmentItemsFromControlRecords :exec
INSERT INTO assessment_items (
  assessment_id,
  framework_item_id,
  control_record_id,
  status,
  priority,
  due_date,
  updated_by
)
SELECT
  $1::uuid,
  cr.framework_item_id,
  cr.id,
  'not_started'::assessment_item_status,
  'medium'::item_priority,
  $2::date,
  $3::uuid
FROM control_records cr
WHERE cr.assessment_id = $1::uuid
`

type CreateAssessmentItemsFromControlRecordsParams struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	DueDate      time.Time `json:"due_date"`
	UpdatedBy    uuid.UUID `json:"updated_by"`
}

func (q *Queries) CreateAssessmentItemsFromControlRecords(ctx context.Context, arg CreateAssessmentItemsFromControlRecordsParams) error {
	_, err := q.db.Exec(ctx, createAssessmentItemsFromControlRecords, arg.AssessmentID, arg.DueDate, arg.UpdatedBy)
	return err
}

const getAssessmentByID = `-- name: GetAssessmentByID :one
SELECT
  a.id, a.framework_id, a.name, a.scope, a.start_date, a.due_date, a.status, a.created_by, a.created_at, a.updated_at,
  f.label AS framework_label,
  f.version AS framework_version
FROM assessments a
JOIN frameworks f ON f.id = a.framework_id
WHERE a.id = $1
`

type GetAssessmentByIDRow struct {
	ID               uuid.UUID        `json:"id"`
	FrameworkID      uuid.UUID        `json:"framework_id"`
	Name             string           `json:"name"`
	Scope            string           `json:"scope"`
	StartDate        time.Time        `json:"start_date"`
	DueDate          time.Time        `json:"due_date"`
	Status           AssessmentStatus `json:"status"`
	CreatedBy        uuid.UUID        `json:"created_by"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
	FrameworkLabel   string           `json:"framework_label"`
	FrameworkVersion string           `json:"framework_version"`
}

func (q *Queries) GetAssessmentByID(ctx context.Context, id uuid.UUID) (GetAssessmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAssessmentByID, id)
	var i GetAssessmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.Name,
		&i.Scope,
		&i.StartDate,
		&i.DueDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FrameworkLabel,
		&i.FrameworkVersion,
	)
	return i, err
}

const listAssessments = `-- name: ListAssessments :many
SELECT
  a.id,
  a.framework_id,
  a.name,
  a.scope,
  a.start_date,
  a.due_date,
  a.status,
  a.created_by,
  a.created_at,
  a.updated_at,
  f.label AS framework_label,
  f.version AS framework_version,
  COUNT(ai.id)::int AS item_count,
  COUNT(ai.id) FILTER (WHERE ai.status IN ('validated', 'not_applicable'))::int AS completed_count
FROM assessments a
JOIN frameworks f ON f.id = a.framework_id
LEFT JOIN assessment_items ai ON ai.assessment_id = a.id
GROUP BY a.id, f.label, f.version
ORDER BY a.created_at DESC
`

type ListAssessmentsRow struct {
	ID               uuid.UUID        `json:"id"`
	FrameworkID      uuid.UUID        `json:"framework_id"`
	Name             string           `json:"name"`
	Scope            string           `json:"scope"`
	StartDate        time.Time        `json:"start_date"`
	DueDate          time.Time        `json:"due_date"`
	Status           AssessmentStatus `json:"status"`
	CreatedBy        uuid.UUID        `json:"created_by"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
	FrameworkLabel   string           `json:"framework_label"`
	FrameworkVersion string           `json:"framework_version"`
	ItemCount        int32            `json:"item_count"`
	CompletedCount   int32            `json:"completed_count"`
}

func (q *Queries) ListAssessments(ctx context.Context) ([]ListAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listAssessments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssessmentsRow
	for rows.Next() {
		var i ListAssessmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkID,
			&i.Name,
			&i.Scope,
			&i.StartDate,
			&i.DueDate,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FrameworkLabel,
			&i.FrameworkVersion,
			&i.ItemCount,
			&i.CompletedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
