// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessment_items.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkSetDueDate = `-- name: BulkSetDueDate :exec
UPDATE assessment_items
SET due_date = $3,
    updated_by = $4,
    updated_at = NOW()
WHERE assessment_id = $1
  AND id = ANY($2::uuid[])
`

type BulkSetDueDateParams struct {
	AssessmentID uuid.UUID   `json:"assessment_id"`
	Column2      []uuid.UUID `json:"column_2"`
	DueDate      time.Time   `json:"due_date"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
}

func (q *Queries) BulkSetDueDate(ctx context.Context, arg BulkSetDueDateParams) error {
	_, err := q.db.Exec(ctx, bulkSetDueDate,
		arg.AssessmentID,
		arg.Column2,
		arg.DueDate,
		arg.UpdatedBy,
	)
	return err
}

const bulkSetPriority = `-- name: BulkSetPriority :exec
UPDATE assessment_items
SET priority = $3,
    updated_by = $4,
    updated_at = NOW()
WHERE assessment_id = $1
  AND id = ANY($2::uuid[])
`

type BulkSetPriorityParams struct {
	AssessmentID uuid.UUID    `json:"assessment_id"`
	Column2      []uuid.UUID  `json:"column_2"`
	Priority     ItemPriority `json:"priority"`
	UpdatedBy    pgtype.UUID  `json:"updated_by"`
}

func (q *Queries) BulkSetPriority(ctx context.Context, arg BulkSetPriorityParams) error {
	_, err := q.db.Exec(ctx, bulkSetPriority,
		arg.AssessmentID,
		arg.Column2,
		arg.Priority,
		arg.UpdatedBy,
	)
	return err
}

const getAssessmentItemDetail = `-- name: GetAssessmentItemDetail :one
SELECT
  ai.id,
  ai.assessment_id,
  ai.framework_item_id,
  ai.control_record_id,
  cr.owner_user_id,
  cr.reviewer_user_id,
  ai.status,
  ai.score,
  ai.priority,
  ai.due_date,
  cr.notes,
  cr.is_not_applicable,
  ai.blocked_reason,
  ai.validated_at,
  ai.validated_by,
  ai.updated_by,
  ai.created_at,
  ai.updated_at,
  a.name AS assessment_name,
  a.scope AS assessment_scope,
  f.label AS framework_label,
  f.version AS framework_version,
  fg.code AS group_code,
  fg.title AS group_title,
  fi.code AS item_code,
  fi.title AS item_title,
  fi.summary AS item_summary,
  fi.description AS item_description,
  fi.asset_class,
  fi.security_function,
  fi.tags,
  ou.name AS owner_name,
  ru.name AS reviewer_name,
  vu.name AS validated_by_name,
  (ai.due_date < CURRENT_DATE AND ai.status NOT IN ('validated', 'not_applicable')) AS is_overdue
FROM assessment_items ai
JOIN control_records cr ON cr.id = ai.control_record_id
JOIN assessments a ON a.id = ai.assessment_id
JOIN frameworks f ON f.id = a.framework_id
JOIN framework_items fi ON fi.id = ai.framework_item_id
JOIN framework_groups fg ON fg.id = fi.framework_group_id
LEFT JOIN users ou ON ou.id = cr.owner_user_id
LEFT JOIN users ru ON ru.id = cr.reviewer_user_id
LEFT JOIN users vu ON vu.id = ai.validated_by
WHERE ai.id = $1
`

type GetAssessmentItemDetailRow struct {
	ID               uuid.UUID            `json:"id"`
	AssessmentID     uuid.UUID            `json:"assessment_id"`
	FrameworkItemID  uuid.UUID            `json:"framework_item_id"`
	ControlRecordID  uuid.UUID            `json:"control_record_id"`
	OwnerUserID      pgtype.UUID          `json:"owner_user_id"`
	ReviewerUserID   pgtype.UUID          `json:"reviewer_user_id"`
	Status           AssessmentItemStatus `json:"status"`
	Score            *int32               `json:"score"`
	Priority         ItemPriority         `json:"priority"`
	DueDate          time.Time            `json:"due_date"`
	Notes            string               `json:"notes"`
	IsNotApplicable  bool                 `json:"is_not_applicable"`
	BlockedReason    *string              `json:"blocked_reason"`
	ValidatedAt      pgtype.Timestamptz   `json:"validated_at"`
	ValidatedBy      pgtype.UUID          `json:"validated_by"`
	UpdatedBy        pgtype.UUID          `json:"updated_by"`
	CreatedAt        time.Time            `json:"created_at"`
	UpdatedAt        time.Time            `json:"updated_at"`
	AssessmentName   string               `json:"assessment_name"`
	AssessmentScope  string               `json:"assessment_scope"`
	FrameworkLabel   string               `json:"framework_label"`
	FrameworkVersion string               `json:"framework_version"`
	GroupCode        string               `json:"group_code"`
	GroupTitle       string               `json:"group_title"`
	ItemCode         string               `json:"item_code"`
	ItemTitle        string               `json:"item_title"`
	ItemSummary      string               `json:"item_summary"`
	ItemDescription  string               `json:"item_description"`
	AssetClass       string               `json:"asset_class"`
	SecurityFunction string               `json:"security_function"`
	Tags             []string             `json:"tags"`
	OwnerName        *string              `json:"owner_name"`
	ReviewerName     *string              `json:"reviewer_name"`
	ValidatedByName  *string              `json:"validated_by_name"`
	IsOverdue        *bool                `json:"is_overdue"`
}

func (q *Queries) GetAssessmentItemDetail(ctx context.Context, id uuid.UUID) (GetAssessmentItemDetailRow, error) {
	row := q.db.QueryRow(ctx, getAssessmentItemDetail, id)
	var i GetAssessmentItemDetailRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.FrameworkItemID,
		&i.ControlRecordID,
		&i.OwnerUserID,
		&i.ReviewerUserID,
		&i.Status,
		&i.Score,
		&i.Priority,
		&i.DueDate,
		&i.Notes,
		&i.IsNotApplicable,
		&i.BlockedReason,
		&i.ValidatedAt,
		&i.ValidatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssessmentName,
		&i.AssessmentScope,
		&i.FrameworkLabel,
		&i.FrameworkVersion,
		&i.GroupCode,
		&i.GroupTitle,
		&i.ItemCode,
		&i.ItemTitle,
		&i.ItemSummary,
		&i.ItemDescription,
		&i.AssetClass,
		&i.SecurityFunction,
		&i.Tags,
		&i.OwnerName,
		&i.ReviewerName,
		&i.ValidatedByName,
		&i.IsOverdue,
	)
	return i, err
}

const listAssessmentItems = `-- name: ListAssessmentItems :many
SELECT
  ai.id,
  ai.assessment_id,
  ai.framework_item_id,
  ai.control_record_id,
  cr.owner_user_id,
  cr.reviewer_user_id,
  ai.status,
  ai.score,
  ai.priority,
  ai.due_date,
  cr.notes,
  ai.blocked_reason,
  ai.validated_at,
  ai.validated_by,
  ai.updated_by,
  ai.created_at,
  ai.updated_at,
  fg.code AS group_code,
  fg.title AS group_title,
  fg.sort_order AS group_sort_order,
  fi.code AS item_code,
  fi.title AS item_title,
  fi.summary AS item_summary,
  fi.tags,
  ou.name AS owner_name,
  ru.name AS reviewer_name,
  (ai.due_date < CURRENT_DATE AND ai.status NOT IN ('validated', 'not_applicable')) AS is_overdue
FROM assessment_items ai
JOIN control_records cr ON cr.id = ai.control_record_id
JOIN framework_items fi ON fi.id = ai.framework_item_id
JOIN framework_groups fg ON fg.id = fi.framework_group_id
LEFT JOIN users ou ON ou.id = cr.owner_user_id
LEFT JOIN users ru ON ru.id = cr.reviewer_user_id
WHERE ai.assessment_id = $1
  AND ($2::text IS NULL OR fg.code = $2::text)
  AND ($3::text IS NULL OR $3::text = ANY(fi.tags))
  AND ($4::text IS NULL OR ai.status::text = $4::text)
  AND ($5::text IS NULL OR cr.owner_user_id::text = $5::text)
  AND ($6::text IS NULL OR cr.reviewer_user_id::text = $6::text)
  AND ($7::boolean IS NULL OR (
    $7::boolean = TRUE
    AND cr.owner_user_id IS NULL
    AND ai.status NOT IN ('validated', 'not_applicable')
  ))
  AND ($8::boolean IS NULL OR (
    $8::boolean = TRUE
    AND ai.due_date < CURRENT_DATE
    AND ai.status NOT IN ('validated', 'not_applicable')
  ))
ORDER BY fi.sort_order, fi.code
`

type ListAssessmentItemsParams struct {
	AssessmentID   uuid.UUID `json:"assessment_id"`
	GroupCode      *string   `json:"group_code"`
	Tag            *string   `json:"tag"`
	Status         *string   `json:"status"`
	OwnerUserID    *string   `json:"owner_user_id"`
	ReviewerUserID *string   `json:"reviewer_user_id"`
	Unassigned     *bool     `json:"unassigned"`
	Overdue        *bool     `json:"overdue"`
}

type ListAssessmentItemsRow struct {
	ID              uuid.UUID            `json:"id"`
	AssessmentID    uuid.UUID            `json:"assessment_id"`
	FrameworkItemID uuid.UUID            `json:"framework_item_id"`
	ControlRecordID uuid.UUID            `json:"control_record_id"`
	OwnerUserID     pgtype.UUID          `json:"owner_user_id"`
	ReviewerUserID  pgtype.UUID          `json:"reviewer_user_id"`
	Status          AssessmentItemStatus `json:"status"`
	Score           *int32               `json:"score"`
	Priority        ItemPriority         `json:"priority"`
	DueDate         time.Time            `json:"due_date"`
	Notes           string               `json:"notes"`
	BlockedReason   *string              `json:"blocked_reason"`
	ValidatedAt     pgtype.Timestamptz   `json:"validated_at"`
	ValidatedBy     pgtype.UUID          `json:"validated_by"`
	UpdatedBy       pgtype.UUID          `json:"updated_by"`
	CreatedAt       time.Time            `json:"created_at"`
	UpdatedAt       time.Time            `json:"updated_at"`
	GroupCode       string               `json:"group_code"`
	GroupTitle      string               `json:"group_title"`
	GroupSortOrder  int32                `json:"group_sort_order"`
	ItemCode        string               `json:"item_code"`
	ItemTitle       string               `json:"item_title"`
	ItemSummary     string               `json:"item_summary"`
	Tags            []string             `json:"tags"`
	OwnerName       *string              `json:"owner_name"`
	ReviewerName    *string              `json:"reviewer_name"`
	IsOverdue       *bool                `json:"is_overdue"`
}

func (q *Queries) ListAssessmentItems(ctx context.Context, arg ListAssessmentItemsParams) ([]ListAssessmentItemsRow, error) {
	rows, err := q.db.Query(ctx, listAssessmentItems,
		arg.AssessmentID,
		arg.GroupCode,
		arg.Tag,
		arg.Status,
		arg.OwnerUserID,
		arg.ReviewerUserID,
		arg.Unassigned,
		arg.Overdue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssessmentItemsRow
	for rows.Next() {
		var i ListAssessmentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.FrameworkItemID,
			&i.ControlRecordID,
			&i.OwnerUserID,
			&i.ReviewerUserID,
			&i.Status,
			&i.Score,
			&i.Priority,
			&i.DueDate,
			&i.Notes,
			&i.BlockedReason,
			&i.ValidatedAt,
			&i.ValidatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupCode,
			&i.GroupTitle,
			&i.GroupSortOrder,
			&i.ItemCode,
			&i.ItemTitle,
			&i.ItemSummary,
			&i.Tags,
			&i.OwnerName,
			&i.ReviewerName,
			&i.IsOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebindFrameworkItemReferences = `-- name: RebindFrameworkItemReferences :exec
WITH eligible_assessments AS (
  SELECT DISTINCT ai.assessment_id
  FROM assessment_items ai
  WHERE ai.framework_item_id = $2::uuid
    AND NOT EXISTS (
      SELECT 1
      FROM assessment_items existing
      WHERE existing.assessment_id = ai.assessment_id
        AND existing.framework_item_id = $1::uuid
    )
    AND NOT EXISTS (
      SELECT 1
      FROM control_records existing
      WHERE existing.assessment_id = ai.assessment_id
        AND existing.framework_item_id = $1::uuid
    )
),
rebound_control_records AS (
  UPDATE control_records cr
  SET framework_item_id = $1::uuid,
      updated_at = NOW()
  FROM eligible_assessments ea
  WHERE cr.framework_item_id = $2::uuid
    AND cr.assessment_id = ea.assessment_id
)
UPDATE assessment_items ai
SET framework_item_id = $1::uuid,
    updated_at = NOW()
FROM eligible_assessments ea
WHERE ai.framework_item_id = $2::uuid
  AND ai.assessment_id = ea.assessment_id
`

type RebindFrameworkItemReferencesParams struct {
	NewFrameworkItemID uuid.UUID `json:"new_framework_item_id"`
	OldFrameworkItemID uuid.UUID `json:"old_framework_item_id"`
}

func (q *Queries) RebindFrameworkItemReferences(ctx context.Context, arg RebindFrameworkItemReferencesParams) error {
	_, err := q.db.Exec(ctx, rebindFrameworkItemReferences, arg.NewFrameworkItemID, arg.OldFrameworkItemID)
	return err
}

const updateAssessmentItem = `-- name: UpdateAssessmentItem :one
UPDATE assessment_items
SET status = $2,
    score = $6,
    priority = $3,
    due_date = $4,
    blocked_reason = $7,
    validated_at = $8,
    validated_by = $9,
    updated_by = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, assessment_id, framework_item_id, status, score, priority, due_date, blocked_reason, validated_at, validated_by, updated_by, created_at, updated_at, control_record_id
`

type UpdateAssessmentItemParams struct {
	ID            uuid.UUID            `json:"id"`
	Status        AssessmentItemStatus `json:"status"`
	Priority      ItemPriority         `json:"priority"`
	DueDate       time.Time            `json:"due_date"`
	UpdatedBy     pgtype.UUID          `json:"updated_by"`
	Score         *int32               `json:"score"`
	BlockedReason *string              `json:"blocked_reason"`
	ValidatedAt   pgtype.Timestamptz   `json:"validated_at"`
	ValidatedBy   pgtype.UUID          `json:"validated_by"`
}

func (q *Queries) UpdateAssessmentItem(ctx context.Context, arg UpdateAssessmentItemParams) (AssessmentItem, error) {
	row := q.db.QueryRow(ctx, updateAssessmentItem,
		arg.ID,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.UpdatedBy,
		arg.Score,
		arg.BlockedReason,
		arg.ValidatedAt,
		arg.ValidatedBy,
	)
	var i AssessmentItem
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.FrameworkItemID,
		&i.Status,
		&i.Score,
		&i.Priority,
		&i.DueDate,
		&i.BlockedReason,
		&i.ValidatedAt,
		&i.ValidatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ControlRecordID,
	)
	return i, err
}
