// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (
  entity_type,
  entity_id,
  action,
  actor_user_id,
  payload_json
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
`

type CreateAuditLogParams struct {
	EntityType  string    `json:"entity_type"`
	EntityID    uuid.UUID `json:"entity_id"`
	Action      string    `json:"action"`
	ActorUserID uuid.UUID `json:"actor_user_id"`
	PayloadJson []byte    `json:"payload_json"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.ActorUserID,
		arg.PayloadJson,
	)
	return err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  control_record_id,
  user_id,
  body
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, user_id, body, created_at, control_record_id
`

type CreateCommentParams struct {
	ControlRecordID uuid.UUID `json:"control_record_id"`
	UserID          uuid.UUID `json:"user_id"`
	Body            string    `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.ControlRecordID, arg.UserID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.ControlRecordID,
	)
	return i, err
}

const createEvidenceLink = `-- name: CreateEvidenceLink :one
INSERT INTO evidence_links (
  control_record_id,
  label,
  url,
  created_by
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, label, url, created_by, created_at, control_record_id
`

type CreateEvidenceLinkParams struct {
	ControlRecordID uuid.UUID `json:"control_record_id"`
	Label           string    `json:"label"`
	Url             string    `json:"url"`
	CreatedBy       uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateEvidenceLink(ctx context.Context, arg CreateEvidenceLinkParams) (EvidenceLink, error) {
	row := q.db.QueryRow(ctx, createEvidenceLink,
		arg.ControlRecordID,
		arg.Label,
		arg.Url,
		arg.CreatedBy,
	)
	var i EvidenceLink
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Url,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ControlRecordID,
	)
	return i, err
}

const listAuditLogByEntity = `-- name: ListAuditLogByEntity :many
SELECT
  a.id, a.entity_type, a.entity_id, a.action, a.actor_user_id, a.payload_json, a.created_at,
  u.name AS actor_name
FROM audit_log a
JOIN users u ON u.id = a.actor_user_id
WHERE a.entity_type = $1
  AND a.entity_id = $2
ORDER BY a.created_at DESC
`

type ListAuditLogByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

type ListAuditLogByEntityRow struct {
	ID          uuid.UUID `json:"id"`
	EntityType  string    `json:"entity_type"`
	EntityID    uuid.UUID `json:"entity_id"`
	Action      string    `json:"action"`
	ActorUserID uuid.UUID `json:"actor_user_id"`
	PayloadJson []byte    `json:"payload_json"`
	CreatedAt   time.Time `json:"created_at"`
	ActorName   string    `json:"actor_name"`
}

func (q *Queries) ListAuditLogByEntity(ctx context.Context, arg ListAuditLogByEntityParams) ([]ListAuditLogByEntityRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogByEntityRow
	for rows.Next() {
		var i ListAuditLogByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorUserID,
			&i.PayloadJson,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByControlRecord = `-- name: ListCommentsByControlRecord :many
SELECT
  c.id, c.user_id, c.body, c.created_at, c.control_record_id,
  u.name AS user_name
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.control_record_id = $1
ORDER BY c.created_at DESC
`

type ListCommentsByControlRecordRow struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	ControlRecordID uuid.UUID `json:"control_record_id"`
	UserName        string    `json:"user_name"`
}

func (q *Queries) ListCommentsByControlRecord(ctx context.Context, controlRecordID uuid.UUID) ([]ListCommentsByControlRecordRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByControlRecord, controlRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByControlRecordRow
	for rows.Next() {
		var i ListCommentsByControlRecordRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.ControlRecordID,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceLinksByControlRecord = `-- name: ListEvidenceLinksByControlRecord :many
SELECT
  e.id, e.label, e.url, e.created_by, e.created_at, e.control_record_id,
  u.name AS created_by_name
FROM evidence_links e
JOIN users u ON u.id = e.created_by
WHERE e.control_record_id = $1
ORDER BY e.created_at DESC
`

type ListEvidenceLinksByControlRecordRow struct {
	ID              uuid.UUID `json:"id"`
	Label           string    `json:"label"`
	Url             string    `json:"url"`
	CreatedBy       uuid.UUID `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	ControlRecordID uuid.UUID `json:"control_record_id"`
	CreatedByName   string    `json:"created_by_name"`
}

func (q *Queries) ListEvidenceLinksByControlRecord(ctx context.Context, controlRecordID uuid.UUID) ([]ListEvidenceLinksByControlRecordRow, error) {
	rows, err := q.db.Query(ctx, listEvidenceLinksByControlRecord, controlRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEvidenceLinksByControlRecordRow
	for rows.Next() {
		var i ListEvidenceLinksByControlRecordRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Url,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ControlRecordID,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
