// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: control_records.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkAssignControlRecordOwner = `-- name: BulkAssignControlRecordOwner :exec
UPDATE control_records
SET owner_user_id = $2,
    updated_at = NOW()
WHERE id = ANY(
  SELECT ai.control_record_id
  FROM assessment_items ai
  WHERE ai.assessment_id = $3
    AND ai.id = ANY($1::uuid[])
)
`

type BulkAssignControlRecordOwnerParams struct {
	Column1      []uuid.UUID `json:"column_1"`
	OwnerUserID  pgtype.UUID `json:"owner_user_id"`
	AssessmentID uuid.UUID   `json:"assessment_id"`
}

func (q *Queries) BulkAssignControlRecordOwner(ctx context.Context, arg BulkAssignControlRecordOwnerParams) error {
	_, err := q.db.Exec(ctx, bulkAssignControlRecordOwner, arg.Column1, arg.OwnerUserID, arg.AssessmentID)
	return err
}

const bulkAssignControlRecordReviewer = `-- name: BulkAssignControlRecordReviewer :exec
UPDATE control_records
SET reviewer_user_id = $2,
    updated_at = NOW()
WHERE id = ANY(
  SELECT ai.control_record_id
  FROM assessment_items ai
  WHERE ai.assessment_id = $3
    AND ai.id = ANY($1::uuid[])
)
`

type BulkAssignControlRecordReviewerParams struct {
	Column1        []uuid.UUID `json:"column_1"`
	ReviewerUserID pgtype.UUID `json:"reviewer_user_id"`
	AssessmentID   uuid.UUID   `json:"assessment_id"`
}

func (q *Queries) BulkAssignControlRecordReviewer(ctx context.Context, arg BulkAssignControlRecordReviewerParams) error {
	_, err := q.db.Exec(ctx, bulkAssignControlRecordReviewer, arg.Column1, arg.ReviewerUserID, arg.AssessmentID)
	return err
}

const copyControlRecordsFromPreviousAssessment = `-- name: CopyControlRecordsFromPreviousAssessment :exec
INSERT INTO control_records (
  assessment_id,
  framework_item_id,
  owner_user_id,
  reviewer_user_id
)
SELECT
  $1::uuid,
  fi.id,
  cr.owner_user_id,
  cr.reviewer_user_id
FROM assessments a
JOIN framework_items fi ON fi.framework_id = a.framework_id
JOIN framework_groups fg ON fg.id = fi.framework_group_id
LEFT JOIN assessment_items ai ON ai.assessment_id = $2::uuid
  AND ai.framework_item_id = fi.id
LEFT JOIN control_records cr ON cr.id = ai.control_record_id
WHERE a.id = $2::uuid
  AND fi.is_active
  AND fg.is_active
`

type CopyControlRecordsFromPreviousAssessmentParams struct {
	AssessmentID         uuid.UUID `json:"assessment_id"`
	PreviousAssessmentID uuid.UUID `json:"previous_assessment_id"`
}

func (q *Queries) CopyControlRecordsFromPreviousAssessment(ctx context.Context, arg CopyControlRecordsFromPreviousAssessmentParams) error {
	_, err := q.db.Exec(ctx, copyControlRecordsFromPreviousAssessment, arg.AssessmentID, arg.PreviousAssessmentID)
	return err
}

const createControlRecordsForAssessment = `-- name: CreateControlRecordsForAssessment :exec
INSERT INTO control_records (assessment_id, framework_item_id)
SELECT $1::uuid, fi.id
FROM framework_items fi
JOIN framework_groups fg ON fg.id = fi.framework_group_id
WHERE fi.framework_id = $2::uuid
  AND fi.is_active
  AND fg.is_active
`

type CreateControlRecordsForAssessmentParams struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	FrameworkID  uuid.UUID `json:"framework_id"`
}

func (q *Queries) CreateControlRecordsForAssessment(ctx context.Context, arg CreateControlRecordsForAssessmentParams) error {
	_, err := q.db.Exec(ctx, createControlRecordsForAssessment, arg.AssessmentID, arg.FrameworkID)
	return err
}

const getControlRecord = `-- name: GetControlRecord :one
SELECT id, assessment_id, framework_item_id, owner_user_id, reviewer_user_id, notes, is_not_applicable, created_at, updated_at FROM control_records WHERE id = $1
`

func (q *Queries) GetControlRecord(ctx context.Context, id uuid.UUID) (ControlRecord, error) {
	row := q.db.QueryRow(ctx, getControlRecord, id)
	var i ControlRecord
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.FrameworkItemID,
		&i.OwnerUserID,
		&i.ReviewerUserID,
		&i.Notes,
		&i.IsNotApplicable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getControlRecordByAssessmentItem = `-- name: GetControlRecordByAssessmentItem :one
SELECT cr.id, cr.assessment_id, cr.framework_item_id, cr.owner_user_id, cr.reviewer_user_id, cr.notes, cr.is_not_applicable, cr.created_at, cr.updated_at
FROM control_records cr
JOIN assessment_items ai ON ai.control_record_id = cr.id
WHERE ai.id = $1
`

func (q *Queries) GetControlRecordByAssessmentItem(ctx context.Context, id uuid.UUID) (ControlRecord, error) {
	row := q.db.QueryRow(ctx, getControlRecordByAssessmentItem, id)
	var i ControlRecord
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.FrameworkItemID,
		&i.OwnerUserID,
		&i.ReviewerUserID,
		&i.Notes,
		&i.IsNotApplicable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateControlRecordNotes = `-- name: UpdateControlRecordNotes :exec
UPDATE control_records
SET notes = $2,
    is_not_applicable = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateControlRecordNotesParams struct {
	ID              uuid.UUID `json:"id"`
	Notes           string    `json:"notes"`
	IsNotApplicable bool      `json:"is_not_applicable"`
}

func (q *Queries) UpdateControlRecordNotes(ctx context.Context, arg UpdateControlRecordNotesParams) error {
	_, err := q.db.Exec(ctx, updateControlRecordNotes, arg.ID, arg.Notes, arg.IsNotApplicable)
	return err
}

const updateControlRecordOwner = `-- name: UpdateControlRecordOwner :exec
UPDATE control_records
SET owner_user_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateControlRecordOwnerParams struct {
	ID          uuid.UUID   `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) UpdateControlRecordOwner(ctx context.Context, arg UpdateControlRecordOwnerParams) error {
	_, err := q.db.Exec(ctx, updateControlRecordOwner, arg.ID, arg.OwnerUserID)
	return err
}

const updateControlRecordReviewer = `-- name: UpdateControlRecordReviewer :exec
UPDATE control_records
SET reviewer_user_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateControlRecordReviewerParams struct {
	ID             uuid.UUID   `json:"id"`
	ReviewerUserID pgtype.UUID `json:"reviewer_user_id"`
}

func (q *Queries) UpdateControlRecordReviewer(ctx context.Context, arg UpdateControlRecordReviewerParams) error {
	_, err := q.db.Exec(ctx, updateControlRecordReviewer, arg.ID, arg.ReviewerUserID)
	return err
}
