// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardOverview = `-- name: GetDashboardOverview :one
SELECT
  COUNT(*)::int AS total_items,
  COUNT(*) FILTER (WHERE status IN ('validated', 'not_applicable'))::int AS completed_items,
  COUNT(*) FILTER (WHERE status = 'ready_for_review')::int AS ready_for_review_items,
  COUNT(*) FILTER (WHERE status = 'blocked')::int AS blocked_items,
  COUNT(*) FILTER (
    WHERE due_date < CURRENT_DATE
      AND status NOT IN ('validated', 'not_applicable')
  )::int AS overdue_items,
  COALESCE(ROUND(AVG(score)::numeric, 1), 0)::numeric AS average_score
FROM assessment_items
WHERE assessment_id = $1
`

type GetDashboardOverviewRow struct {
	TotalItems          int32          `json:"total_items"`
	CompletedItems      int32          `json:"completed_items"`
	ReadyForReviewItems int32          `json:"ready_for_review_items"`
	BlockedItems        int32          `json:"blocked_items"`
	OverdueItems        int32          `json:"overdue_items"`
	AverageScore        pgtype.Numeric `json:"average_score"`
}

func (q *Queries) GetDashboardOverview(ctx context.Context, assessmentID uuid.UUID) (GetDashboardOverviewRow, error) {
	row := q.db.QueryRow(ctx, getDashboardOverview, assessmentID)
	var i GetDashboardOverviewRow
	err := row.Scan(
		&i.TotalItems,
		&i.CompletedItems,
		&i.ReadyForReviewItems,
		&i.BlockedItems,
		&i.OverdueItems,
		&i.AverageScore,
	)
	return i, err
}

const listDashboardGroupCompletion = `-- name: ListDashboardGroupCompletion :many
SELECT
  fg.code AS group_code,
  fg.title AS group_title,
  COUNT(ai.id)::int AS total_items,
  COUNT(ai.id) FILTER (WHERE ai.status IN ('validated', 'not_applicable'))::int AS completed_items,
  COALESCE(ROUND(AVG(ai.score)::numeric, 1), 0)::numeric AS average_score
FROM assessment_items ai
JOIN framework_items fi ON fi.id = ai.framework_item_id
JOIN framework_groups fg ON fg.id = fi.framework_group_id
WHERE ai.assessment_id = $1
GROUP BY fg.id
ORDER BY fg.sort_order ASC, fg.code ASC
`

type ListDashboardGroupCompletionRow struct {
	GroupCode      string         `json:"group_code"`
	GroupTitle     string         `json:"group_title"`
	TotalItems     int32          `json:"total_items"`
	CompletedItems int32          `json:"completed_items"`
	AverageScore   pgtype.Numeric `json:"average_score"`
}

func (q *Queries) ListDashboardGroupCompletion(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardGroupCompletionRow, error) {
	rows, err := q.db.Query(ctx, listDashboardGroupCompletion, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardGroupCompletionRow
	for rows.Next() {
		var i ListDashboardGroupCompletionRow
		if err := rows.Scan(
			&i.GroupCode,
			&i.GroupTitle,
			&i.TotalItems,
			&i.CompletedItems,
			&i.AverageScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardLowScoreItems = `-- name: ListDashboardLowScoreItems :many
SELECT
  ai.id,
  fi.code AS item_code,
  fi.title AS item_title,
  fg.code AS group_code,
  COALESCE(ou.name, 'Unassigned') AS owner_name,
  ai.score
FROM assessment_items ai
JOIN control_records cr ON cr.id = ai.control_record_id
JOIN framework_items fi ON fi.id = ai.framework_item_id
JOIN framework_groups fg ON fg.id = fi.framework_group_id
LEFT JOIN users ou ON ou.id = cr.owner_user_id
WHERE ai.assessment_id = $1
  AND ai.score IS NOT NULL
  AND ai.score <= 2
ORDER BY ai.score ASC, fg.sort_order ASC, fi.sort_order ASC, fi.code ASC
LIMIT 10
`

type ListDashboardLowScoreItemsRow struct {
	ID        uuid.UUID `json:"id"`
	ItemCode  string    `json:"item_code"`
	ItemTitle string    `json:"item_title"`
	GroupCode string    `json:"group_code"`
	OwnerName string    `json:"owner_name"`
	Score     *int32    `json:"score"`
}

func (q *Queries) ListDashboardLowScoreItems(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardLowScoreItemsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardLowScoreItems, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardLowScoreItemsRow
	for rows.Next() {
		var i ListDashboardLowScoreItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.ItemTitle,
			&i.GroupCode,
			&i.OwnerName,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardOverdueItems = `-- name: ListDashboardOverdueItems :many
SELECT
  ai.id,
  fi.code AS item_code,
  fi.title AS item_title,
  fg.code AS group_code,
  COALESCE(ou.name, 'Unassigned') AS owner_name,
  ai.due_date
FROM assessment_items ai
JOIN control_records cr ON cr.id = ai.control_record_id
JOIN framework_items fi ON fi.id = ai.framework_item_id
JOIN framework_groups fg ON fg.id = fi.framework_group_id
LEFT JOIN users ou ON ou.id = cr.owner_user_id
WHERE ai.assessment_id = $1
  AND ai.due_date < CURRENT_DATE
  AND ai.status NOT IN ('validated', 'not_applicable')
ORDER BY ai.due_date ASC, fg.sort_order ASC, fi.sort_order ASC, fi.code ASC
LIMIT 10
`

type ListDashboardOverdueItemsRow struct {
	ID        uuid.UUID `json:"id"`
	ItemCode  string    `json:"item_code"`
	ItemTitle string    `json:"item_title"`
	GroupCode string    `json:"group_code"`
	OwnerName string    `json:"owner_name"`
	DueDate   time.Time `json:"due_date"`
}

func (q *Queries) ListDashboardOverdueItems(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardOverdueItemsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardOverdueItems, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardOverdueItemsRow
	for rows.Next() {
		var i ListDashboardOverdueItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.ItemTitle,
			&i.GroupCode,
			&i.OwnerName,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardOwnerWorkload = `-- name: ListDashboardOwnerWorkload :many
SELECT
  u.id,
  u.name,
  COUNT(ai.id)::int AS total_items,
  COUNT(ai.id) FILTER (WHERE ai.status IN ('validated', 'not_applicable'))::int AS completed_items,
  COUNT(ai.id) FILTER (
    WHERE ai.due_date < CURRENT_DATE
      AND ai.status NOT IN ('validated', 'not_applicable')
  )::int AS overdue_items
FROM users u
JOIN control_records cr ON cr.owner_user_id = u.id
JOIN assessment_items ai ON ai.control_record_id = cr.id
WHERE ai.assessment_id = $1
GROUP BY u.id
ORDER BY total_items DESC, u.name ASC
`

type ListDashboardOwnerWorkloadRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	TotalItems     int32     `json:"total_items"`
	CompletedItems int32     `json:"completed_items"`
	OverdueItems   int32     `json:"overdue_items"`
}

func (q *Queries) ListDashboardOwnerWorkload(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardOwnerWorkloadRow, error) {
	rows, err := q.db.Query(ctx, listDashboardOwnerWorkload, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardOwnerWorkloadRow
	for rows.Next() {
		var i ListDashboardOwnerWorkloadRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TotalItems,
			&i.CompletedItems,
			&i.OverdueItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardReviewQueue = `-- name: ListDashboardReviewQueue :many
SELECT
  ai.id,
  fi.code AS item_code,
  fi.title AS item_title,
  fg.code AS group_code,
  COALESCE(ou.name, 'Unassigned') AS owner_name,
  COALESCE(ru.name, 'Unassigned') AS reviewer_name,
  ai.updated_at
FROM assessment_items ai
JOIN control_records cr ON cr.id = ai.control_record_id
JOIN framework_items fi ON fi.id = ai.framework_item_id
JOIN framework_groups fg ON fg.id = fi.framework_group_id
LEFT JOIN users ou ON ou.id = cr.owner_user_id
LEFT JOIN users ru ON ru.id = cr.reviewer_user_id
WHERE ai.assessment_id = $1
  AND ai.status = 'ready_for_review'
ORDER BY ai.updated_at DESC
LIMIT 10
`

type ListDashboardReviewQueueRow struct {
	ID           uuid.UUID `json:"id"`
	ItemCode     string    `json:"item_code"`
	ItemTitle    string    `json:"item_title"`
	GroupCode    string    `json:"group_code"`
	OwnerName    string    `json:"owner_name"`
	ReviewerName string    `json:"reviewer_name"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ListDashboardReviewQueue(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardReviewQueueRow, error) {
	rows, err := q.db.Query(ctx, listDashboardReviewQueue, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardReviewQueueRow
	for rows.Next() {
		var i ListDashboardReviewQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemCode,
			&i.ItemTitle,
			&i.GroupCode,
			&i.OwnerName,
			&i.ReviewerName,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
