// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: frameworks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFramework = `-- name: CreateFramework :one
INSERT INTO frameworks (
  slug,
  label,
  version,
  status
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, slug, label, version, status, created_at, updated_at
`

type CreateFrameworkParams struct {
	Slug    string `json:"slug"`
	Label   string `json:"label"`
	Version string `json:"version"`
	Status  string `json:"status"`
}

func (q *Queries) CreateFramework(ctx context.Context, arg CreateFrameworkParams) (Framework, error) {
	row := q.db.QueryRow(ctx, createFramework,
		arg.Slug,
		arg.Label,
		arg.Version,
		arg.Status,
	)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFrameworkGroup = `-- name: CreateFrameworkGroup :one
INSERT INTO framework_groups (
  framework_id,
  code,
  title,
  summary,
  description,
  sort_order
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, framework_id, code, title, summary, description, is_active, sort_order
`

type CreateFrameworkGroupParams struct {
	FrameworkID uuid.UUID `json:"framework_id"`
	Code        string    `json:"code"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Description string    `json:"description"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) CreateFrameworkGroup(ctx context.Context, arg CreateFrameworkGroupParams) (FrameworkGroup, error) {
	row := q.db.QueryRow(ctx, createFrameworkGroup,
		arg.FrameworkID,
		arg.Code,
		arg.Title,
		arg.Summary,
		arg.Description,
		arg.SortOrder,
	)
	var i FrameworkGroup
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const createFrameworkItem = `-- name: CreateFrameworkItem :one
INSERT INTO framework_items (
  framework_id,
  framework_group_id,
  code,
  title,
  summary,
  description,
  sort_order,
  asset_class,
  security_function,
  tags
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
RETURNING id, framework_id, framework_group_id, code, title, summary, asset_class, security_function, tags, description, is_active, sort_order
`

type CreateFrameworkItemParams struct {
	FrameworkID      uuid.UUID `json:"framework_id"`
	FrameworkGroupID uuid.UUID `json:"framework_group_id"`
	Code             string    `json:"code"`
	Title            string    `json:"title"`
	Summary          string    `json:"summary"`
	Description      string    `json:"description"`
	SortOrder        int32     `json:"sort_order"`
	AssetClass       string    `json:"asset_class"`
	SecurityFunction string    `json:"security_function"`
	Tags             []string  `json:"tags"`
}

func (q *Queries) CreateFrameworkItem(ctx context.Context, arg CreateFrameworkItemParams) (FrameworkItem, error) {
	row := q.db.QueryRow(ctx, createFrameworkItem,
		arg.FrameworkID,
		arg.FrameworkGroupID,
		arg.Code,
		arg.Title,
		arg.Summary,
		arg.Description,
		arg.SortOrder,
		arg.AssetClass,
		arg.SecurityFunction,
		arg.Tags,
	)
	var i FrameworkItem
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.FrameworkGroupID,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.AssetClass,
		&i.SecurityFunction,
		&i.Tags,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const deactivateMissingFrameworkGroups = `-- name: DeactivateMissingFrameworkGroups :exec
UPDATE framework_groups
SET is_active = FALSE
WHERE framework_id = $1::uuid
  AND NOT (code = ANY($2::text[]))
`

type DeactivateMissingFrameworkGroupsParams struct {
	FrameworkID uuid.UUID `json:"framework_id"`
	Codes       []string  `json:"codes"`
}

func (q *Queries) DeactivateMissingFrameworkGroups(ctx context.Context, arg DeactivateMissingFrameworkGroupsParams) error {
	_, err := q.db.Exec(ctx, deactivateMissingFrameworkGroups, arg.FrameworkID, arg.Codes)
	return err
}

const deactivateMissingFrameworkItems = `-- name: DeactivateMissingFrameworkItems :exec
UPDATE framework_items
SET is_active = FALSE
WHERE framework_id = $1::uuid
  AND NOT (code = ANY($2::text[]))
`

type DeactivateMissingFrameworkItemsParams struct {
	FrameworkID uuid.UUID `json:"framework_id"`
	Codes       []string  `json:"codes"`
}

func (q *Queries) DeactivateMissingFrameworkItems(ctx context.Context, arg DeactivateMissingFrameworkItemsParams) error {
	_, err := q.db.Exec(ctx, deactivateMissingFrameworkItems, arg.FrameworkID, arg.Codes)
	return err
}

const deleteFramework = `-- name: DeleteFramework :exec
DELETE FROM frameworks WHERE id = $1
`

func (q *Queries) DeleteFramework(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFramework, id)
	return err
}

const getFrameworkByID = `-- name: GetFrameworkByID :one
SELECT id, slug, label, version, status, created_at, updated_at
FROM frameworks
WHERE id = $1
`

func (q *Queries) GetFrameworkByID(ctx context.Context, id uuid.UUID) (Framework, error) {
	row := q.db.QueryRow(ctx, getFrameworkByID, id)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkBySlugVersion = `-- name: GetFrameworkBySlugVersion :one
SELECT id, slug, label, version, status, created_at, updated_at
FROM frameworks
WHERE slug = $1
  AND version = $2
`

type GetFrameworkBySlugVersionParams struct {
	Slug    string `json:"slug"`
	Version string `json:"version"`
}

func (q *Queries) GetFrameworkBySlugVersion(ctx context.Context, arg GetFrameworkBySlugVersionParams) (Framework, error) {
	row := q.db.QueryRow(ctx, getFrameworkBySlugVersion, arg.Slug, arg.Version)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkItemByCode = `-- name: GetFrameworkItemByCode :one
SELECT id, framework_id, framework_group_id, code, title, summary, asset_class, security_function, tags, description, is_active, sort_order
FROM framework_items
WHERE framework_id = $1
  AND code = $2
`

type GetFrameworkItemByCodeParams struct {
	FrameworkID uuid.UUID `json:"framework_id"`
	Code        string    `json:"code"`
}

func (q *Queries) GetFrameworkItemByCode(ctx context.Context, arg GetFrameworkItemByCodeParams) (FrameworkItem, error) {
	row := q.db.QueryRow(ctx, getFrameworkItemByCode, arg.FrameworkID, arg.Code)
	var i FrameworkItem
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.FrameworkGroupID,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.AssetClass,
		&i.SecurityFunction,
		&i.Tags,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const listFrameworkGroupsByFramework = `-- name: ListFrameworkGroupsByFramework :many
SELECT
  fg.id, fg.framework_id, fg.code, fg.title, fg.summary, fg.description, fg.is_active, fg.sort_order,
  COUNT(fi.id)::int AS item_count
FROM framework_groups fg
LEFT JOIN framework_items fi ON fi.framework_group_id = fg.id
  AND fi.is_active
WHERE fg.framework_id = $1
  AND fg.is_active
GROUP BY fg.id
ORDER BY fg.sort_order
`

type ListFrameworkGroupsByFrameworkRow struct {
	ID          uuid.UUID `json:"id"`
	FrameworkID uuid.UUID `json:"framework_id"`
	Code        string    `json:"code"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	SortOrder   int32     `json:"sort_order"`
	ItemCount   int32     `json:"item_count"`
}

func (q *Queries) ListFrameworkGroupsByFramework(ctx context.Context, frameworkID uuid.UUID) ([]ListFrameworkGroupsByFrameworkRow, error) {
	rows, err := q.db.Query(ctx, listFrameworkGroupsByFramework, frameworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFrameworkGroupsByFrameworkRow
	for rows.Next() {
		var i ListFrameworkGroupsByFrameworkRow
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkID,
			&i.Code,
			&i.Title,
			&i.Summary,
			&i.Description,
			&i.IsActive,
			&i.SortOrder,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameworksWithCounts = `-- name: ListFrameworksWithCounts :many
SELECT
  f.id, f.slug, f.label, f.version, f.status, f.created_at, f.updated_at,
  COUNT(DISTINCT fg.id)::int AS group_count,
  COUNT(DISTINCT fi.id)::int AS item_count
FROM frameworks f
LEFT JOIN framework_groups fg ON fg.framework_id = f.id
  AND fg.is_active
LEFT JOIN framework_items fi ON fi.framework_id = f.id
  AND fi.is_active
GROUP BY f.id
ORDER BY f.created_at DESC
`

type ListFrameworksWithCountsRow struct {
	ID         uuid.UUID `json:"id"`
	Slug       string    `json:"slug"`
	Label      string    `json:"label"`
	Version    string    `json:"version"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	GroupCount int32     `json:"group_count"`
	ItemCount  int32     `json:"item_count"`
}

func (q *Queries) ListFrameworksWithCounts(ctx context.Context) ([]ListFrameworksWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listFrameworksWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFrameworksWithCountsRow
	for rows.Next() {
		var i ListFrameworksWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupCount,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFrameworkGroup = `-- name: UpsertFrameworkGroup :one
INSERT INTO framework_groups (
  framework_id,
  code,
  title,
  summary,
  description,
  sort_order
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (framework_id, code) DO UPDATE
  SET title       = EXCLUDED.title,
      summary     = EXCLUDED.summary,
      description = EXCLUDED.description,
      sort_order  = EXCLUDED.sort_order,
      is_active   = TRUE
RETURNING id, framework_id, code, title, summary, description, is_active, sort_order
`

type UpsertFrameworkGroupParams struct {
	FrameworkID uuid.UUID `json:"framework_id"`
	Code        string    `json:"code"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Description string    `json:"description"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) UpsertFrameworkGroup(ctx context.Context, arg UpsertFrameworkGroupParams) (FrameworkGroup, error) {
	row := q.db.QueryRow(ctx, upsertFrameworkGroup,
		arg.FrameworkID,
		arg.Code,
		arg.Title,
		arg.Summary,
		arg.Description,
		arg.SortOrder,
	)
	var i FrameworkGroup
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const upsertFrameworkItem = `-- name: UpsertFrameworkItem :one
INSERT INTO framework_items (
  framework_id,
  framework_group_id,
  code,
  title,
  summary,
  description,
  sort_order,
  asset_class,
  security_function,
  tags
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
ON CONFLICT (framework_id, code) DO UPDATE
  SET framework_group_id  = EXCLUDED.framework_group_id,
      title               = EXCLUDED.title,
      summary             = EXCLUDED.summary,
      description         = EXCLUDED.description,
      sort_order          = EXCLUDED.sort_order,
      asset_class         = EXCLUDED.asset_class,
      security_function   = EXCLUDED.security_function,
      tags                = EXCLUDED.tags,
      is_active           = TRUE
RETURNING id, framework_id, framework_group_id, code, title, summary, asset_class, security_function, tags, description, is_active, sort_order
`

type UpsertFrameworkItemParams struct {
	FrameworkID      uuid.UUID `json:"framework_id"`
	FrameworkGroupID uuid.UUID `json:"framework_group_id"`
	Code             string    `json:"code"`
	Title            string    `json:"title"`
	Summary          string    `json:"summary"`
	Description      string    `json:"description"`
	SortOrder        int32     `json:"sort_order"`
	AssetClass       string    `json:"asset_class"`
	SecurityFunction string    `json:"security_function"`
	Tags             []string  `json:"tags"`
}

func (q *Queries) UpsertFrameworkItem(ctx context.Context, arg UpsertFrameworkItemParams) (FrameworkItem, error) {
	row := q.db.QueryRow(ctx, upsertFrameworkItem,
		arg.FrameworkID,
		arg.FrameworkGroupID,
		arg.Code,
		arg.Title,
		arg.Summary,
		arg.Description,
		arg.SortOrder,
		arg.AssetClass,
		arg.SecurityFunction,
		arg.Tags,
	)
	var i FrameworkItem
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.FrameworkGroupID,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.AssetClass,
		&i.SecurityFunction,
		&i.Tags,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}
