// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssessmentItemStatus string

const (
	AssessmentItemStatusNotStarted     AssessmentItemStatus = "not_started"
	AssessmentItemStatusInProgress     AssessmentItemStatus = "in_progress"
	AssessmentItemStatusReadyForReview AssessmentItemStatus = "ready_for_review"
	AssessmentItemStatusValidated      AssessmentItemStatus = "validated"
	AssessmentItemStatusNotApplicable  AssessmentItemStatus = "not_applicable"
	AssessmentItemStatusBlocked        AssessmentItemStatus = "blocked"
)

func (e *AssessmentItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssessmentItemStatus(s)
	case string:
		*e = AssessmentItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssessmentItemStatus: %T", src)
	}
	return nil
}

type NullAssessmentItemStatus struct {
	AssessmentItemStatus AssessmentItemStatus `json:"assessment_item_status"`
	Valid                bool                 `json:"valid"` // Valid is true if AssessmentItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssessmentItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssessmentItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssessmentItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssessmentItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssessmentItemStatus), nil
}

type AssessmentStatus string

const (
	AssessmentStatusDraft     AssessmentStatus = "draft"
	AssessmentStatusActive    AssessmentStatus = "active"
	AssessmentStatusCompleted AssessmentStatus = "completed"
	AssessmentStatusArchived  AssessmentStatus = "archived"
)

func (e *AssessmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssessmentStatus(s)
	case string:
		*e = AssessmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssessmentStatus: %T", src)
	}
	return nil
}

type NullAssessmentStatus struct {
	AssessmentStatus AssessmentStatus `json:"assessment_status"`
	Valid            bool             `json:"valid"` // Valid is true if AssessmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssessmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssessmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssessmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssessmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssessmentStatus), nil
}

type ItemPriority string

const (
	ItemPriorityLow      ItemPriority = "low"
	ItemPriorityMedium   ItemPriority = "medium"
	ItemPriorityHigh     ItemPriority = "high"
	ItemPriorityCritical ItemPriority = "critical"
)

func (e *ItemPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemPriority(s)
	case string:
		*e = ItemPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemPriority: %T", src)
	}
	return nil
}

type NullItemPriority struct {
	ItemPriority ItemPriority `json:"item_priority"`
	Valid        bool         `json:"valid"` // Valid is true if ItemPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemPriority) Scan(value interface{}) error {
	if value == nil {
		ns.ItemPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemPriority), nil
}

type Assessment struct {
	ID          uuid.UUID        `json:"id"`
	FrameworkID uuid.UUID        `json:"framework_id"`
	Name        string           `json:"name"`
	Scope       string           `json:"scope"`
	StartDate   time.Time        `json:"start_date"`
	DueDate     time.Time        `json:"due_date"`
	Status      AssessmentStatus `json:"status"`
	CreatedBy   uuid.UUID        `json:"created_by"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

type AssessmentItem struct {
	ID              uuid.UUID            `json:"id"`
	AssessmentID    uuid.UUID            `json:"assessment_id"`
	FrameworkItemID uuid.UUID            `json:"framework_item_id"`
	Status          AssessmentItemStatus `json:"status"`
	Score           *int32               `json:"score"`
	Priority        ItemPriority         `json:"priority"`
	DueDate         time.Time            `json:"due_date"`
	BlockedReason   *string              `json:"blocked_reason"`
	ValidatedAt     pgtype.Timestamptz   `json:"validated_at"`
	ValidatedBy     pgtype.UUID          `json:"validated_by"`
	UpdatedBy       pgtype.UUID          `json:"updated_by"`
	CreatedAt       time.Time            `json:"created_at"`
	UpdatedAt       time.Time            `json:"updated_at"`
	ControlRecordID uuid.UUID            `json:"control_record_id"`
}

type AuditLog struct {
	ID          uuid.UUID `json:"id"`
	EntityType  string    `json:"entity_type"`
	EntityID    uuid.UUID `json:"entity_id"`
	Action      string    `json:"action"`
	ActorUserID uuid.UUID `json:"actor_user_id"`
	PayloadJson []byte    `json:"payload_json"`
	CreatedAt   time.Time `json:"created_at"`
}

type Comment struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	ControlRecordID uuid.UUID `json:"control_record_id"`
}

type ControlRecord struct {
	ID              uuid.UUID   `json:"id"`
	AssessmentID    uuid.UUID   `json:"assessment_id"`
	FrameworkItemID uuid.UUID   `json:"framework_item_id"`
	OwnerUserID     pgtype.UUID `json:"owner_user_id"`
	ReviewerUserID  pgtype.UUID `json:"reviewer_user_id"`
	Notes           string      `json:"notes"`
	IsNotApplicable bool        `json:"is_not_applicable"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type EvidenceLink struct {
	ID              uuid.UUID `json:"id"`
	Label           string    `json:"label"`
	Url             string    `json:"url"`
	CreatedBy       uuid.UUID `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	ControlRecordID uuid.UUID `json:"control_record_id"`
}

type Framework struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Label     string    `json:"label"`
	Version   string    `json:"version"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type FrameworkGroup struct {
	ID          uuid.UUID `json:"id"`
	FrameworkID uuid.UUID `json:"framework_id"`
	Code        string    `json:"code"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
}

type FrameworkItem struct {
	ID               uuid.UUID `json:"id"`
	FrameworkID      uuid.UUID `json:"framework_id"`
	FrameworkGroupID uuid.UUID `json:"framework_group_id"`
	Code             string    `json:"code"`
	Title            string    `json:"title"`
	Summary          string    `json:"summary"`
	AssetClass       string    `json:"asset_class"`
	SecurityFunction string    `json:"security_function"`
	Tags             []string  `json:"tags"`
	Description      string    `json:"description"`
	IsActive         bool      `json:"is_active"`
}

type User struct {
	ID                 uuid.UUID `json:"id"`
	Name               string    `json:"name"`
	Email              string    `json:"email"`
	PasswordHash       string    `json:"password_hash"`
	IsAdmin            bool      `json:"is_admin"`
	MustChangePassword bool      `json:"must_change_password"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}
