// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BulkAssignControlRecordOwner(ctx context.Context, arg BulkAssignControlRecordOwnerParams) error
	BulkAssignControlRecordReviewer(ctx context.Context, arg BulkAssignControlRecordReviewerParams) error
	BulkSetDueDate(ctx context.Context, arg BulkSetDueDateParams) error
	BulkSetPriority(ctx context.Context, arg BulkSetPriorityParams) error
	CopyControlRecordsFromPreviousAssessment(ctx context.Context, arg CopyControlRecordsFromPreviousAssessmentParams) error
	CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error)
	CreateAssessmentItemsFromControlRecords(ctx context.Context, arg CreateAssessmentItemsFromControlRecordsParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateControlRecordsForAssessment(ctx context.Context, arg CreateControlRecordsForAssessmentParams) error
	CreateEvidenceLink(ctx context.Context, arg CreateEvidenceLinkParams) (EvidenceLink, error)
	CreateFramework(ctx context.Context, arg CreateFrameworkParams) (Framework, error)
	CreateFrameworkGroup(ctx context.Context, arg CreateFrameworkGroupParams) (FrameworkGroup, error)
	CreateFrameworkItem(ctx context.Context, arg CreateFrameworkItemParams) (FrameworkItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateMissingFrameworkGroups(ctx context.Context, arg DeactivateMissingFrameworkGroupsParams) error
	DeactivateMissingFrameworkItems(ctx context.Context, arg DeactivateMissingFrameworkItemsParams) error
	DeleteFramework(ctx context.Context, id uuid.UUID) error
	GetAssessmentByID(ctx context.Context, id uuid.UUID) (GetAssessmentByIDRow, error)
	GetAssessmentItemDetail(ctx context.Context, id uuid.UUID) (GetAssessmentItemDetailRow, error)
	GetControlRecord(ctx context.Context, id uuid.UUID) (ControlRecord, error)
	GetControlRecordByAssessmentItem(ctx context.Context, id uuid.UUID) (ControlRecord, error)
	GetDashboardOverview(ctx context.Context, assessmentID uuid.UUID) (GetDashboardOverviewRow, error)
	GetFrameworkByID(ctx context.Context, id uuid.UUID) (Framework, error)
	GetFrameworkBySlugVersion(ctx context.Context, arg GetFrameworkBySlugVersionParams) (Framework, error)
	GetFrameworkItemByCode(ctx context.Context, arg GetFrameworkItemByCodeParams) (FrameworkItem, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAssessmentIDsEligibleForFrameworkItemRebind(ctx context.Context, arg ListAssessmentIDsEligibleForFrameworkItemRebindParams) ([]uuid.UUID, error)
	ListAssessmentItems(ctx context.Context, arg ListAssessmentItemsParams) ([]ListAssessmentItemsRow, error)
	ListAssessments(ctx context.Context) ([]ListAssessmentsRow, error)
	ListAuditLogByEntity(ctx context.Context, arg ListAuditLogByEntityParams) ([]ListAuditLogByEntityRow, error)
	ListCommentsByControlRecord(ctx context.Context, controlRecordID uuid.UUID) ([]ListCommentsByControlRecordRow, error)
	ListDashboardGroupCompletion(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardGroupCompletionRow, error)
	ListDashboardLowScoreItems(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardLowScoreItemsRow, error)
	ListDashboardOverdueItems(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardOverdueItemsRow, error)
	ListDashboardOwnerWorkload(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardOwnerWorkloadRow, error)
	ListDashboardReviewQueue(ctx context.Context, assessmentID uuid.UUID) ([]ListDashboardReviewQueueRow, error)
	ListEvidenceLinksByControlRecord(ctx context.Context, controlRecordID uuid.UUID) ([]ListEvidenceLinksByControlRecordRow, error)
	ListFrameworkGroupsByFramework(ctx context.Context, frameworkID uuid.UUID) ([]ListFrameworkGroupsByFrameworkRow, error)
	ListFrameworksWithCounts(ctx context.Context) ([]ListFrameworksWithCountsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	RebindAssessmentItemsFrameworkItem(ctx context.Context, arg RebindAssessmentItemsFrameworkItemParams) error
	RebindControlRecordsFrameworkItem(ctx context.Context, arg RebindControlRecordsFrameworkItemParams) error
	UpdateAssessmentItem(ctx context.Context, arg UpdateAssessmentItemParams) (AssessmentItem, error)
	UpdateControlRecordNotes(ctx context.Context, arg UpdateControlRecordNotesParams) error
	UpdateControlRecordOwner(ctx context.Context, arg UpdateControlRecordOwnerParams) error
	UpdateControlRecordReviewer(ctx context.Context, arg UpdateControlRecordReviewerParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertFrameworkGroup(ctx context.Context, arg UpsertFrameworkGroupParams) (FrameworkGroup, error)
	UpsertFrameworkItem(ctx context.Context, arg UpsertFrameworkItemParams) (FrameworkItem, error)
}

var _ Querier = (*Queries)(nil)
