// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name,
  email,
  password_hash,
  role,
  must_change_password
) VALUES (
  $1,
  lower($2),
  $3,
  $4,
  $5
)
RETURNING id, name, email, password_hash, must_change_password, created_at, updated_at, role
`

type CreateUserParams struct {
	Name               string   `json:"name"`
	Lower              string   `json:"lower"`
	PasswordHash       string   `json:"password_hash"`
	Role               UserRole `json:"role"`
	MustChangePassword bool     `json:"must_change_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Lower,
		arg.PasswordHash,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, must_change_password, created_at, updated_at, role
FROM users
WHERE email = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, must_change_password, created_at, updated_at, role
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password_hash, must_change_password, created_at, updated_at, role
FROM users
ORDER BY CASE role
  WHEN 'admin' THEN 0
  WHEN 'assessment_manager' THEN 1
  WHEN 'editor' THEN 2
  ELSE 3
END,
name ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    role = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password_hash, must_change_password, created_at, updated_at, role
`

type UpdateUserParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Role UserRole  `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    must_change_password = FALSE,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPasswordReset = `-- name: UpdateUserPasswordReset :exec
UPDATE users
SET password_hash = $2,
    must_change_password = TRUE,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordResetParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordReset(ctx context.Context, arg UpdateUserPasswordResetParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordReset, arg.ID, arg.PasswordHash)
	return err
}
